server:
  port: 8080

spring:
  application:
    name: mproject-gateway
  config:
    import: optional:configserver:/
  cloud:
    config:
      discovery:
        service-id: mproject-config-server
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
